name: Deploy to Amazon ECR

on:
  push:
    branches:
      - main   # or master depending on your repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        run: |
          IMAGE_TAG=latest
          docker build -t regression_api:$IMAGE_TAG .
          docker tag regression_api:$IMAGE_TAG 665168932309.dkr.ecr.eu-north-1.amazonaws.com/regression_api:$IMAGE_TAG
          docker push 665168932309.dkr.ecr.eu-north-1.amazonaws.com/regression_api:$IMAGE_TAG
